# Copyright (c) 2026 Artronah1
#
# SPDX-License-Identifier: MulanPubL-2.0
name: Release

on:
  release:
    types: [created]
  # Позволяет запустить вручную из вкладки Actions
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goarch: arm64
            name: ksd-arm64
          - goarch: amd64
            name: ksd-amd64
          - goarch: mipsle
            name: ksd-mipsle
            extra: GOMIPS=softfloat
          - goarch: mips
            name: ksd-mips
            extra: GOMIPS=softfloat

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build
        env:
          GOOS: linux
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: '0'
        run: |
          ${{ matrix.extra }} go build -trimpath -ldflags="-s -w" -o ${{ matrix.name }} .

      - name: Upload artifact to release
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'release'
        with:
          files: ${{ matrix.name }}
